/// Money arithmetic that matches the server, exactly.
///
/// ## Why this exists
///
/// `PriceConverter.toFixed` used to `.floor()` its result. The backend
/// (`PlaceNewOrder.php`) uses PHP's `round()` for every monetary field —
/// `order_amount`, `delivery_charge`, `total_tax_amount`, coupon and store
/// discounts, per-item `price` and `total_add_on_price`. So the client
/// truncated where the server rounded, and every price in the app could sit one
/// minor unit below what the customer was actually charged. `10.999` displayed
/// as `10.99` and billed as `11.00`.
///
/// The server is authoritative: it recomputes `order_amount` on every order
/// regardless of what the client sends. The client's only job is to *predict*
/// that number exactly, so the quote a customer agrees to is the amount they
/// pay.
///
/// ## Why `.round()` alone is not enough
///
/// Dart's `double.round()` operates on the binary value, PHP's `round()` does
/// not. PHP applies a "pre-rounding" correction (see `_php_math_round` in
/// ext/standard/math.c) that undoes IEEE-754 representation error before
/// rounding. The two disagree on exactly the values that matter in pricing:
///
/// ```text
/// value     PHP round(v,2)    Dart (v*100).round()/100
/// 1.005     1.01              1.0      <-- mismatch
/// 8.995     9.0               8.99     <-- mismatch
/// ```
///
/// `1.005` in IEEE-754 is actually 1.00499999999999989…, so `* 100` gives
/// 100.49999999999999 and a naive round goes down. PHP notices that the value
/// is within representation error of a .5 boundary and corrects first.
/// [roundLikeServer] ports that algorithm. It is verified against 51 vectors
/// generated by PHP itself — see `test/contract/fixtures/rounding_vectors.json`
/// and `tool/generate_rounding_vectors.php`.
///
/// ## Prefer minor units
///
/// Rounding parity fixes the *symptom*. The cure is to not use floats for money
/// at all: [Money] holds an integer count of piasters, so addition, scaling and
/// summation are exact and no rounding happens until the value is formatted for
/// display. New pricing code should use [Money]; [roundLikeServer] exists for
/// the boundary where we still receive doubles from JSON and must match the
/// server's own rounding of them.
library;

import 'dart:math' as math;

/// Rounds [value] to [digits] decimal places exactly as PHP's `round()` does.
///
/// This is a port of `_php_math_round`. Do not "simplify" it to
/// `(v * 100).round() / 100` — that is the bug this replaces, and the contract
/// test will fail.
double roundLikeServer(double value, int digits) {
  if (value.isNaN || value.isInfinite || value == 0.0) return value;

  final double f1 = math.pow(10.0, digits.abs()).toDouble();
  double tmp = digits >= 0 ? value * f1 : value / f1;

  // Values this large have no fractional part left to round, and scaling them
  // further would lose precision. PHP bails out here too.
  if (tmp.abs() >= 1e15) return value;

  // The pre-rounding correction. `precisionPlaces` is how many decimal places
  // are still trustworthy for a number of this magnitude, given a double's ~15
  // significant digits. If the requested `digits` is inside that window, round
  // there first to snap the value back onto the decimal the author wrote, then
  // do the real rounding.
  final int precisionPlaces =
      14 - (math.log(value.abs()) / math.ln10).floor();
  if (precisionPlaces > digits && precisionPlaces - 15 < digits) {
    final double f2 =
        math.pow(10.0, (precisionPlaces - digits).abs()).toDouble();
    tmp = tmp * f2;
    tmp = tmp >= 0.0 ? (tmp + 0.5).floorToDouble() : (tmp - 0.5).ceilToDouble();
    tmp = tmp / f2;
  }

  // Round half away from zero, which is what PHP does (and what a customer
  // expects). Dart's `.round()` also rounds half away from zero, but only
  // after the correction above has run.
  tmp = tmp >= 0.0 ? (tmp + 0.5).floorToDouble() : (tmp - 0.5).ceilToDouble();

  // Scaling back up can reintroduce drift (e.g. 1.0100000000000002). Normalise
  // through the decimal representation, as PHP does with its own
  // `php_round_helper` epilogue.
  if (tmp.isFinite) {
    tmp = double.parse(tmp.toStringAsExponential(15));
  }

  return digits >= 0 ? tmp / f1 : tmp * f1;
}

/// An exact monetary amount, stored as a whole number of minor units
/// (piasters for EGP).
///
/// Float money is wrong in ways that only show up at scale: summing a 30-item
/// grocery cart accumulates representation error, and the total the customer
/// sees can differ from the sum of the lines they can read on screen. Integers
/// make addition and subtraction exact, so the only rounding in the whole
/// pipeline happens once, at [format].
class Money implements Comparable<Money> {
  /// The amount in minor units. 1250 == 12.50 EGP.
  final int minorUnits;

  const Money.fromMinorUnits(this.minorUnits);

  static const Money zero = Money.fromMinorUnits(0);

  /// Builds a [Money] from a major-unit double, typically one just parsed out
  /// of a JSON payload.
  ///
  /// Rounds with [roundLikeServer] so a price the server rounded to 1.01 does
  /// not become 1.00 on the way in.
  factory Money.fromMajorUnits(double amount, {int digits = 2}) {
    final double rounded = roundLikeServer(amount, digits);
    final int scale = _pow10(digits);
    return Money.fromMinorUnits((rounded * scale).round());
  }

  /// The amount as a major-unit double, for the display and payload layers that
  /// still speak in doubles.
  double toMajorUnits({int digits = 2}) => minorUnits / _pow10(digits);

  Money operator +(Money other) =>
      Money.fromMinorUnits(minorUnits + other.minorUnits);

  Money operator -(Money other) =>
      Money.fromMinorUnits(minorUnits - other.minorUnits);

  /// Multiplies by a whole quantity. Exact — this is the cart line case.
  Money operator *(int quantity) =>
      Money.fromMinorUnits(minorUnits * quantity);

  /// Applies a rate (a tax or percentage discount) and rounds the result to a
  /// whole minor unit, half away from zero, matching the server.
  Money scaledBy(double rate) {
    final double scaled = minorUnits * rate;
    return Money.fromMinorUnits(
      scaled >= 0 ? (scaled + 0.5).floor() : (scaled - 0.5).ceil(),
    );
  }

  /// Percentage helper: `price.percent(15)` is 15% of `price`.
  Money percent(double percentage) => scaledBy(percentage / 100.0);

  bool get isZero => minorUnits == 0;
  bool get isNegative => minorUnits < 0;

  /// Clamps at zero. Discounts must never push a line negative.
  Money get clampedToZero =>
      minorUnits < 0 ? Money.zero : this;

  static Money sum(Iterable<Money> amounts) =>
      amounts.fold(Money.zero, (a, b) => a + b);

  @override
  int compareTo(Money other) => minorUnits.compareTo(other.minorUnits);

  bool operator <(Money other) => minorUnits < other.minorUnits;
  bool operator >(Money other) => minorUnits > other.minorUnits;
  bool operator <=(Money other) => minorUnits <= other.minorUnits;
  bool operator >=(Money other) => minorUnits >= other.minorUnits;

  @override
  bool operator ==(Object other) =>
      other is Money && other.minorUnits == minorUnits;

  @override
  int get hashCode => minorUnits.hashCode;

  @override
  String toString() => 'Money(${toMajorUnits()})';

  static int _pow10(int n) {
    int r = 1;
    for (int i = 0; i < n; i++) {
      r *= 10;
    }
    return r;
  }
}
