import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:waddy_app/util/money.dart';

/// Locks the client's money rounding to the server's.
///
/// The vectors in `fixtures/rounding_vectors.json` are GENERATED BY PHP — run
/// `php tool/generate_rounding_vectors.php > test/contract/fixtures/rounding_vectors.json`
/// against the backend's PHP version to refresh them. The server is
/// authoritative (`PlaceNewOrder.php` recomputes `order_amount` on every
/// order), so this test asserts the client predicts the server, not that the
/// client is "correct" in the abstract.
///
/// If this test fails, the client and server disagree about what a customer
/// will be charged. That is a release blocker, not a rounding nit.
void main() {
  group('rounding parity with PHP round()', () {
    late List<dynamic> vectors;

    setUpAll(() {
      final file = File('test/contract/fixtures/rounding_vectors.json');
      expect(
        file.existsSync(),
        isTrue,
        reason: 'rounding vectors missing — regenerate with '
            'php tool/generate_rounding_vectors.php',
      );
      vectors = jsonDecode(file.readAsStringSync())['vectors'] as List<dynamic>;
    });

    test('every PHP-generated vector matches roundLikeServer', () {
      expect(vectors, isNotEmpty);

      final List<String> mismatches = <String>[];
      for (final dynamic v in vectors) {
        final double input = (v['input'] as num).toDouble();
        final int digits = v['digits'] as int;
        final double expected = (v['expected'] as num).toDouble();
        final double actual = roundLikeServer(input, digits);

        if (actual != expected) {
          mismatches.add(
            'round($input, $digits): php=$expected dart=$actual',
          );
        }
      }

      expect(
        mismatches,
        isEmpty,
        reason: 'client/server rounding divergence:\n${mismatches.join('\n')}',
      );
    });

    test('the specific traps that a naive .round() gets wrong', () {
      // These are the cases that make `(v * 100).round() / 100` insufficient.
      // 1.005 is really 1.00499999999999989 in IEEE-754; PHP corrects, Dart
      // does not. Keeping them called out by name so a future "simplification"
      // fails loudly here rather than silently in production.
      expect(roundLikeServer(1.005, 2), 1.01);
      expect(roundLikeServer(8.995, 2), 9.0);
      expect(roundLikeServer(2.675, 2), 2.68);
      expect(roundLikeServer(1.115, 2), 1.12);
      expect(roundLikeServer(0.045, 2), 0.05);
    });

    test('the original truncation bug stays fixed', () {
      // `toFixed` used to floor. These are the values it got wrong.
      expect(roundLikeServer(10.999, 2), 11.0);
      expect(roundLikeServer(10.999, 2), isNot(10.99));
    });

    test('negatives round half away from zero, like PHP', () {
      expect(roundLikeServer(-2.675, 2), -2.68);
      expect(roundLikeServer(-10.999, 2), -11.0);
    });

    test('degenerate inputs are returned untouched', () {
      expect(roundLikeServer(0.0, 2), 0.0);
      expect(roundLikeServer(double.nan, 2).isNaN, isTrue);
      expect(roundLikeServer(double.infinity, 2), double.infinity);
    });
  });

  group('Money — exact arithmetic in minor units', () {
    test('summing a large cart does not drift', () {
      // The float version of this (0.1 + 0.1 + ... 30 times) is 3.0000000000000004.
      final List<Money> lines =
          List<Money>.filled(30, Money.fromMajorUnits(0.1));
      expect(Money.sum(lines), Money.fromMajorUnits(3.0));
      expect(Money.sum(lines).minorUnits, 300);
    });

    test('quantity multiplication is exact', () {
      final Money line = Money.fromMajorUnits(19.99);
      expect((line * 3).toMajorUnits(), 59.97);
      expect((line * 7).minorUnits, 13993);
    });

    test('percentage applies half-away-from-zero', () {
      // 14% VAT on 100.00 EGP
      expect(Money.fromMajorUnits(100.0).percent(14).toMajorUnits(), 14.0);
      // A rate that lands exactly on a half minor unit rounds up.
      expect(const Money.fromMinorUnits(101).percent(50).minorUnits, 51);
    });

    test('fromMajorUnits honours server rounding on the way in', () {
      // A server value of 1.005 must become 101 piasters, not 100.
      expect(Money.fromMajorUnits(1.005).minorUnits, 101);
      expect(Money.fromMajorUnits(8.995).minorUnits, 900);
    });

    test('discounts never push a line negative', () {
      final Money price = Money.fromMajorUnits(10.0);
      final Money discount = Money.fromMajorUnits(15.0);
      expect((price - discount).clampedToZero, Money.zero);
    });

    test('equality and ordering are value-based', () {
      expect(Money.fromMajorUnits(5.0), const Money.fromMinorUnits(500));
      expect(Money.fromMajorUnits(5.0) > Money.fromMajorUnits(4.99), isTrue);
      // Built at runtime on purpose: two separately-constructed Money values
      // with the same minor units must collapse to one set entry, which is
      // what value equality means here.
      expect(
        <Money>{
          Money.fromMajorUnits(1.0),
          // ignore: prefer_const_constructors
          Money.fromMinorUnits(50 + 50),
        }.length,
        1,
      );
    });
  });
}
